### ISSUE TITLE
Building project from visual studio.

### ISSUE THREAD

**Issue by Minilei89** [Esquiviasrj/UnitBuilderV1#2]
So for GitHub, there no shortcut for pulling the files and not compiling + building then through GitHub. Instead each person has to have their own project built and we just have to pull and push the source files. Yesterday I was on my desktop and couldn't build the project without running into errors so I wanna see what properties you set to run the project.  I followed the set up in the sfml documentation but kept running into errors. Anyway we can talk about it after the acm meeting.

**Comment by Esquiviasrj** [comment]
Yeah we can take a look at it tonight
